package VWB::REST::Manager;

use Moose;
use Cwd;
use Data::Dumper;
use File::Path;
use FindBin;
use File::Slurp;
use Term::ANSIColor;

use VWB::REST::Logger;
use VWB::REST::Config::Manager;
use VWB::REST::DBUtil::Factory;

use constant TRUE  => 1;
use constant FALSE => 0;

use constant DEFAULT_TEST_MODE => TRUE;

use constant DEFAULT_USERNAME =>  getlogin || getpwuid($<) || $ENV{USER} || "";

use constant DEFAULT_OUTDIR => '/tmp/' . DEFAULT_USERNAME . '/' . File::Basename::basename($0) . '/' . time();

use constant DEFAULT_INDIR => File::Spec->rel2abs(cwd());

## Singleton support
my $instance;

has 'test_mode' => (
    is       => 'rw',
    isa      => 'Bool',
    writer   => 'setTestMode',
    reader   => 'getTestMode',
    required => FALSE,
    default  => DEFAULT_TEST_MODE
    );

has 'config_file' => (
    is       => 'rw',
    isa      => 'Str',
    writer   => 'setConfigfile',
    reader   => 'getConfigfile',
    required => FALSE,
    );

has 'outdir' => (
    is       => 'rw',
    isa      => 'Str',
    writer   => 'setOutdir',
    reader   => 'getOutdir',
    required => FALSE,
    default  => DEFAULT_OUTDIR
    );

has 'report_file' => (
    is       => 'rw',
    isa      => 'Str',
    writer   => 'setReportFile',
    reader   => 'getReportFile',
    required => FALSE
    );

sub getInstance {

    if (!defined($instance)){

        $instance = new VWB::REST::Manager(@_);

        if (!defined($instance)){

            confess "Could not instantiate VWB::REST::Manager";
        }
    }
    return $instance;
}

sub BUILD {

    my $self = shift;

    $self->_initLogger(@_);

    $self->_initConfigManager(@_);

    $self->_initDBUtilFactory(@_);

    $self->_initDBUtil(@_);

    $self->{_logger}->info("Instantiated ". __PACKAGE__);
}


sub _initLogger {

    my $self = shift;

    my $logger = Log::Log4perl->get_logger(__PACKAGE__);

    if (!defined($logger)){
        confess "logger was not defined";
    }

    $self->{_logger} = $logger;
}

sub _initConfigManager {

    my $self = shift;

    my $manager = VWB::REST::Config::Manager::getInstance(@_);
    if (!defined($manager)){
        $self->{_logger}->logconfess("Could not instantiate VWB::REST::Config::Manager");
    }

    $self->{_config_manager} = $manager;
}

sub _initDBUtilFactory {

    my $self = shift;

    my $factory = VWB::REST::DBUtil::Factory::getInstance(@_);
    if (!defined($factory)){
        $self->{_logger}->logconfess("Could not instantiate VWB::REST::DBUtil::Factory");
    }

    $factory->setType("mongodb");

    $self->{_dbutil_factory} = $factory;
}

sub _initDBUtil {

    my $self = shift;

    my $dbutil = $self->{_dbutil_factory}->create(@_);
    if (!defined($dbutil)){
        $self->{_logger}->logconfess("Could not instantiate VWB::REST::DBUtil");
    }

    $self->{_dbutil} = $dbutil;
}

sub _execute_cmd {

    my $self = shift;
    my ($cmd) = @_;
    
    my @results;
 
    $self->{_logger}->info("About to execute '$cmd'");
    
    eval {
    	@results = qx($cmd);
    };

    if ($?){
    	$self->{_logger}->logconfess("Encountered some error while attempting to execute '$cmd' : $! $@");
    }

    chomp @results;

    return \@results;
}

sub printBoldRed {

    my ($msg) = @_;
    print color 'bold red';
    print $msg . "\n";
    print color 'reset';
}

sub printYellow {

    my ($msg) = @_;
    print color 'yellow';
    print $msg . "\n";
    print color 'reset';
}

sub printGreen {

    my ($msg) = @_;
    print color 'green';
    print $msg . "\n";
    print color 'reset';
}

sub printBrightBlue {

    my ($msg) = @_;
    print color 'bright_blue';
    print $msg . "\n";
    print color 'reset';
}

## Will insert the autogenerated methods here
sub add_new_file{

	my $self = shift;

	## Add a new file to
	
    return $self->{_dbutil}->add_new_file(@_);
};

sub get_files_unique_identifier_list{

	my $self = shift;

	## Retrieve list of file unique identifiers.
	
    return $self->{_dbutil}->get_files_unique_identifier_list(@_);
};

sub get_file_details_by_unique_identifier{

	my $self = shift;

	## Retrieve file details by unique identifier.
	
    return $self->{_dbutil}->get_file_details_by_unique_identifier(@_);
};


no Moose;
__PACKAGE__->meta->make_immutable;

__END__


=head1 NAME

 VWB::REST::Manager
 

=head1 VERSION

 1.0

=head1 SYNOPSIS

 use VWB::REST::Manager;
 my $manager = VWB::REST::Manager::getInstance();
 $manager->run();

=head1 AUTHOR

 Jaideep Sundaram

 Copyright Jaideep Sundaram

=head1 METHODS

=over 4

=cut